export const getSalesReportColumns = () => [
  { header: "Invoice No", accessorKey: "invoice.bill_no" },
  { header: "Invoice Date", accessorKey: "invoice.bill_date" },
  { header: "Store", accessorFn: row => row.invoice.store?.store_name || "", id: "store_name" },
  { header: "Customer", accessorFn: row => row.invoice.customer?.customer_name || "", id: "customer_name" },
  { header: "Item", accessorFn: row => row.item?.name || "", id: "item_name" },
  { header: "Batch", accessorKey: "batch_no" },
  // { header: "Expiry", accessorKey: "expiry_date" },
  // { header: "Pack Qty", accessorKey: "pack_qty" },
  { header: "Qty", accessorKey: "qty" },
  { header: "Rate", accessorKey: "rate" },
  { header: "Disc %", accessorKey: "discount_percent" },
  { header: "Taxable Amount", accessorKey: "taxable_amount" },
  { header: "GST %", accessorKey: "gst_percent" },
  { header: "GST Amount", accessorKey: "gst_amount" },
  { header: "Total (With GST)", accessorKey: "line_total_with_gst" },
];
